# Application Info
info:
  app:
    name: test
    description: test
    version: 1.0.0


# Server Config
server:
  port: 8080
  servlet:
    context-path: /


# Application Debug & Logging
wrap-rest-config:
  response:
    includeDebugInfo: true
    enableGlobalCors: true
  logging:
    servlet:
      request: BASIC, QUERY_PARAMS, HEADER, BODY
      response: BASIC, QUERY_PARAMS, HEADER, BODY
  controller:
    enableErrorCodesCtrl: true
  swagger:
    basePackage: in.cjcj


# Cache Config
caching:
  enable: false
  configs:
    cache-name:
      eviction: MAXIMUM_SIZE
      maximumSize: 1
      expireAfterAccess: 1
      expireAfterWrite: 1


# OAuth2 Resource Server Configuration
resource-server:
  enable: true
  issuer-uri: "https://login.microsoftonline.com/274e7bcc-09e1-4464-8187-eb991bfcf27e/v2.0"
  verify-claims:
    name: value
  authorityMapping:
    name: prefix
  whitelistUrls:
    - "**"
    - "**/swagger-resources/**"
    - "/swagger-ui.html"
    - "/v2/api-docs"
    - "/v3/api-docs"
    - "/webjars/**"


# OAuth2 Rest Template Configuration
resource-client:
  registrations:
    github:
      clientId: test
      clientSecret: test
      scope: scope
      tokenUri: tokenUri
