# Application Info
info:
  app:
    name: test
    description: test
    version: 1.0.0


# Server Config
server:
  port: 8080
  servlet:
    context-path: /

# Application Debug & Logging
wrap-rest-config:
  response:
    includeDebugInfo: true
    enableGlobalCors: true
  logging:
    servlet:
      request: BASIC, QUERY_PARAMS, HEADER, BODY
      response: BASIC, QUERY_PARAMS, HEADER, BODY
  controller:
    enableErrorCodesCtrl: true
  swagger:
    basePackage: in.cjcj